# clojure:
  # build: 'api-clojure'
# go:
  # build: 'api-go'
grape:
  build: "api-grape"
  ports:
    - "9292:9292"
hapi:
  build: "api-hapi"
  expose:
    - "9292"
railsapi:
  build: "api-rails-api"
  expose:
    - "9292"
cassandra:
  image: "mashape/cassandra"
  expose:
    - "9042"
kong:
  image: "mashape/kong"
  ports:
    - "8000:8000"
    - "8001:8001"
  links:
    - "cassandra"
    # - "clojure"
    # - "go"
    - "grape"
    - "hapi"
    - "railsapi"
